export const CONTROL_LOCAL = {
  MOVE_ACTIONBUTTON: 'LOCAL.CHANGE_SEGMENT_USER',
};

export const DEVICE = {
  CONNECTED_INTERNET: 'CONNECTED_INTERNET',
};

export const SETTING = {
  UPDATE_SETTING: 'UPDATE_SETTING',
};

export const USER_SCREEN_CONTROL = {
  VALUE_Y_SCROLL: 'LOCAL.VALUE_Y_SCROLL',
  TAB_INDEX: 'LOCAL.TAB_INDEX',
};

export const USER = {
  LOGIN: 'USER.LOGIN',
  LOGOUT: 'USER.LOGOUT',
  GET_CURRENT_USER_IN_DB: 'USER.GET_CURRENT_USER_IN_DB',
  CHECK_ACCESS_TOKEN_IS_ACTIVE: 'USER.CHECK_ACCESS_TOKEN_IS_ACTIVE',
  REMOVE_ERROR: 'USER.REMOVE_ERROR',
  UPDATE_AVATAR: 'USER.UPDATE_AVATAR',
  CHANGE_PASSWORD: 'USER.CHANGE_PASSWORD',
  RESULT_CHANGE_PASSWORD: 'USER.RESULT_CHANGE_PASSWORD',
  RELOAD_CURRENT_USER_DATA: 'SAGA.RELOAD_CURRENT_USER_DATA',
};

export const STUDENT = {
  FECTH_STUDENT_INFOR: 'STUDENT.FECTH_STUDENT_INFOR',
  UPDATE_AVATAR: 'STUDENT.UPDATE_AVATAR',
  UPLOAD_AVATAR: 'STUDENT.UPLOAD_AVATAR',
  REMOVE_ERROR: 'STUDENT.REMOVE_ERROR',
};

export const STUDENT_PROFILE = {
  FECTH_STUDENT_PROFILE: 'STUDENT_PROFILE.FECTH_STUDENT_PROFILE',
};

export const FEEDBACK = {
  SEND_FEEDBACK: 'FEEDBACK.SEND_FEEDBACK',
  STATUS_FEEDBACK: 'FEEDBACK.STATUS_FEEDBACK',
};

export const SAGA = {
  ///////////////////////////////////////////////////////
  //User login
  USER_LOGIN_SUCCESS: 'SAGA.USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'SAGA.USER_LOGIN_FAILED',

  GET_CURRENT_USER_IN_DB_SUCCESS: 'SAGA.GET_CURRENT_USER_IN_DB_SUCCESS',
  GET_CURRENT_USER_IN_DB_FAILED: 'SAGA.GET_CURRENT_USER_IN_DB_FAILED',

  CHECK_ACCESS_TOKEN_IS_ACTIVE_SUCCESS:
    'SAGA.CHECK_ACCESS_TOKEN_IS_ACTIVE_SUCCESS',
  CHECK_ACCESS_TOKEN_IS_ACTIVE_FAILED: 'SAGA.CHECK_ACCESS_TOKEN_IS_ACTIVE',

  ///////////////////////////////////////////////////////
  //User Logout
  USER_LOGOUT: 'SAGA.USERLOGOUT',
  USER_LOGOUT_SUCCESS: 'SAGA.USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILED: 'SAGA.USER_LOGOUT_FAILED',

  ///////////////////////////////////////////////////////
  //Student

  FECTH_STUDENT_INFOR_SUCCESS: 'SAGA.FECTH_STUDENT_INFOR_SUCCESS',
  FECTH_STUDENT_INFOR_FAILED: 'SAGA.FECTH_STUDENT_INFOR_FAILED',

  ///////////////////////////////////////////////////////
  //Student profile

  FECTH_STUDENT_PROFILE_SUCCESS: 'SAGA.FECTH_STUDENT_PROFILE_SUCCESS',
  FECTH_STUDENT_PROFILE_FAILED: 'SAGA.FECTH_STUDENT_PROFILE_FAILED',

  //////////////////////////////////////////////////////
  //Upload - Update avatar
  UPDATE_AVATAR_SUCCESS: 'SAGA.UPDATE_AVATAR_SUCCESS',
  UPDATE_AVATAR_FAILED: 'SAGA.UPDATE_AVATAR_FAILED',
  UPLOAD_AVATAR_SUCCESS: 'SAGA.UPLOAD_AVATAR_SUCCESS',
  UPLOAD_AVATAR_FAILED: 'SAGA.UPLOAD_AVATAR_FAILED',

  //////////////////////////////////////////////////////
  //Lấy dữ liệu tin tức trang chủ
  LISTNEWHOMESCREEN: {
    LOAD_YOUTUBE: 'SAGA.LISTNEWHOMESCREEN.LOAD_YOUTUBE',
    RESULT_YOUTUBE: 'SAGA.LISTNEWHOMESCREEN.RESULT_YOUTUBE',

    LOAD_FANPAGE: 'SAGA.LISTNEWHOMESCREEN.LOAD_FANPAGE',
    RESULT_FANPAGE: 'SAGA.LISTNEWHOMESCREEN.RESULT_FANPAGE',

    LOAD_WEBHOU: 'SAGA.LISTNEWHOMESCREEN.LOAD_WEBHOU',
    RESULT_WEBHOU: 'SAGA.LISTNEWHOMESCREEN.RESULT_WEBHOU',

    LOAD_CNTT: 'SAGA.LISTNEWHOMESCREEN.LOAD_CNTT',
    RESULT_CNTT: 'SAGA.LISTNEWHOMESCREEN.RESULT_CNTT',

    LOAD_CNSH: 'SAGA.LISTNEWHOMESCREEN.LOAD_CNSH',
    RESULT_CNSH: 'SAGA.LISTNEWHOMESCREEN.RESULT_CNSH',

    LOAD_LUAT: 'SAGA.LISTNEWHOMESCREEN.LOAD_LUAT',
    RESULT_LUAT: 'SAGA.LISTNEWHOMESCREEN.RESULT_LUAT',

    LOAD_TDCN: 'SAGA.LISTNEWHOMESCREEN.LOAD_TDCN',
    RESULT_TDCN: 'SAGA.LISTNEWHOMESCREEN.RESULT_TDCN',

    LOAD_DTTX: 'SAGA.LISTNEWHOMESCREEN.LOAD_DTTX',
    RESULT_DTTX: 'SAGA.LISTNEWHOMESCREEN.RESULT_DTTX',

    LOAD_CNDT_TT: 'SAGA.LISTNEWHOMESCREEN.LOAD_CNDT_TT',
    RESULT_CNDT_TT: 'SAGA.LISTNEWHOMESCREEN.RESULT_CNDT_TT',

    LOAD_KIENTRUC: 'SAGA.LISTNEWHOMESCREEN.LOAD_KIENTRUC',
    RESULT_KIENTRUC: 'SAGA.LISTNEWHOMESCREEN.RESULT_KIENTRUC',

    LOAD_TIENGANH: 'SAGA.LISTNEWHOMESCREEN.LOAD_TIENGANH',
    RESULT_TIENGANH: 'SAGA.LISTNEWHOMESCREEN.RESULT_TIENGANH',

    LOAD_KINHTE: 'SAGA.LISTNEWHOMESCREEN.LOAD_KINHTE',
    RESULT_KINHTE: 'SAGA.LISTNEWHOMESCREEN.RESULT_KINHTE',

    LOAD_TIENGQT: 'SAGA.LISTNEWHOMESCREEN.LOAD_TIENGQT',
    RESULT_TIENGQT: 'SAGA.LISTNEWHOMESCREEN.RESULT_TIENGQT',

    LOAD_DULICH: 'SAGA.LISTNEWHOMESCREEN.LOAD_DULICH',
    RESULT_DULICH: 'SAGA.LISTNEWHOMESCREEN.RESULT_DULICH',

    LOAD_TCNH: 'SAGA.LISTNEWHOMESCREEN.LOAD_TCNH',
    RESULT_TCNH: 'SAGA.LISTNEWHOMESCREEN.RESULT_TCNH',

    LOAD_SAUDH: 'SAGA.LISTNEWHOMESCREEN.LOAD_SAUDH',
    RESULT_SAUDH: 'SAGA.LISTNEWHOMESCREEN.RESULT_SAUDH',

    LOAD_E_LEARNING: 'SAGA.LISTNEWHOMESCREEN.LOAD_E_LEARNING',
    RESULT_E_LEARNING: 'SAGA.LISTNEWHOMESCREEN.RESULT_E_LEARNING',

    LOAD_TTHOUDANANG: 'SAGA.LISTNEWHOMESCREEN.LOAD_TTHOUDANANG',
    RESULT_TTHOUDANANG: 'SAGA.LISTNEWHOMESCREEN.RESULT_TTHOUDANANG',

    LOAD_TT_NN_BDNH: 'SAGA.LISTNEWHOMESCREEN.LOAD_TT_NN_BDNH',
    RESULT_TT_NN_BDNH: 'SAGA.LISTNEWHOMESCREEN.RESULT_TT_NN_BDNH',
  },
};
